import './globals.css';
import type { Metadata } from 'next';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

import Nav from '@/components/nav';
import ReactQueryProvider from '@/app/react-query-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ReactQueryProvider>
          <ReactQueryDevtools initialIsOpen={false} />
          <Nav />
          <main className='container'>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
